tests: fix type annotation in test_pyproject
Fix failing mypy check by using correct type annotatation in tests. The
`Container` ABC does not include `items()`.

```
tests/test_pyproject.py:48: error: "Container[Any]" has no attribute "items"  [attr-defined]
```

Signed-off-by: Christian Heimes <cheimes@redhat.com>